const CITIES=[
{name:"الدوحة - قطر",label:"الدوحة",lat:25.2854,lng:51.5310,tz:3},
{name:"عمّان - الأردن",label:"عمّان",lat:31.9539,lng:35.9106,tz:3},
{name:"معان - الأردن",label:"معان",lat:30.1962,lng:35.7341,tz:3},
{name:"الكرك - الأردن",label:"الكرك",lat:31.1853,lng:35.7047,tz:3},
{name:"القدس - فلسطين",label:"القدس",lat:31.7683,lng:35.2137,tz:3},
{name:"مكة المكرمة - السعودية",label:"مكة",lat:21.3891,lng:39.8579,tz:3},
{name:"الرياض - السعودية",label:"الرياض",lat:24.7136,lng:46.6753,tz:3},
{name:"دبي - الإمارات",label:"دبي",lat:25.2048,lng:55.2708,tz:4},
{name:"لندن - بريطانيا",label:"لندن",lat:51.5072,lng:-.1276,tz:1},
{name:"إسطنبول - تركيا",label:"إسطنبول",lat:41.0082,lng:28.9784,tz:3}
];
const KAABA={lat:21.422487,lng:39.826206};
let selectedCity=JSON.parse(localStorage.getItem("selectedCity"))||CITIES[0];
let prayerMethod=localStorage.getItem("prayerMethod")||"4";
let darkMode=localStorage.getItem("darkMode")==="true";
let alertsEnabled=localStorage.getItem("alertsEnabled")==="true";
let alertSettings=JSON.parse(localStorage.getItem("alertSettings"))||{before:true,atTime:true};
let wakeBeforeFajr=Number(localStorage.getItem("wakeBeforeFajr")||35);
let sleepHours=Number(localStorage.getItem("sleepHours")||7);
let prayerTimes={}, alertTimers=[], deferredPrompt, qiblaBearing=0, smoothedHeading=null;
const el=id=>document.getElementById(id);
function toEnglish(v){return String(v).replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d)).replace(/[۰-۹]/g,d=>"۰۱۲۳۴۵۶۷۸۹".indexOf(d))}
function setText(id,v){el(id).textContent=toEnglish(v)}
function initTabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));b.classList.add("active");el(b.dataset.tab).classList.add("active")})}
function initCity(){citySelect.innerHTML="";CITIES.forEach((c,i)=>{let o=document.createElement("option");o.value=i;o.textContent=c.name;if(c.label===selectedCity.label&&Number(c.lat).toFixed(3)===Number(selectedCity.lat).toFixed(3))o.selected=true;citySelect.appendChild(o)});citySelect.onchange=async()=>{selectedCity=CITIES[Number(citySelect.value)];localStorage.setItem("selectedCity",JSON.stringify(selectedCity));smoothedHeading=null;await refreshAll()}}
function initSettings(){prayerMethod.value=prayerMethod;el("prayerMethod").value=prayerMethod;el("wakeBeforeFajr").value=wakeBeforeFajr;el("sleepHours").value=sleepHours;el("notifyBefore").checked=alertSettings.before;el("notifyAtTime").checked=alertSettings.atTime;el("saveSettings").onclick=async()=>{prayerMethod=el("prayerMethod").value;wakeBeforeFajr=Number(el("wakeBeforeFajr").value||35);sleepHours=Number(el("sleepHours").value||7);alertSettings.before=el("notifyBefore").checked;alertSettings.atTime=el("notifyAtTime").checked;localStorage.setItem("prayerMethod",prayerMethod);localStorage.setItem("wakeBeforeFajr",wakeBeforeFajr);localStorage.setItem("sleepHours",sleepHours);localStorage.setItem("alertSettings",JSON.stringify(alertSettings));await refreshAll();alert("تم حفظ الإعدادات")}}
function applyDark(){document.body.classList.toggle("dark",darkMode);darkModeButton.textContent=darkMode?"☀️ الوضع الفاتح":"🌙 الوضع الداكن"}
darkModeButton.onclick=()=>{darkMode=!darkMode;localStorage.setItem("darkMode",String(darkMode));applyDark()};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installButton.style.display="block"});
installButton.onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installButton.style.display="none"};
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");
function rad(d){return d*Math.PI/180} function deg(r){return r*180/Math.PI} function n360(v){v%=360;return v<0?v+360:v} function n24(v){v%=24;return v<0?v+24:v}
function dayOfYear(d){let s=new Date(Date.UTC(d.getFullYear(),0,0));return Math.floor((Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-s)/86400000)}
function sunTime(date,rise){let zen=90.833,N=dayOfYear(date),lngH=selectedCity.lng/15,t=N+((rise?6:18)-lngH)/24,M=.9856*t-3.289,L=n360(M+1.916*Math.sin(rad(M))+.020*Math.sin(rad(2*M))+282.634),RA=n360(deg(Math.atan(.91764*Math.tan(rad(L))))),Lq=Math.floor(L/90)*90,RAq=Math.floor(RA/90)*90;RA=(RA+(Lq-RAq))/15;let sinD=.39782*Math.sin(rad(L)),cosD=Math.cos(Math.asin(sinD)),cosH=(Math.cos(rad(zen))-(sinD*Math.sin(rad(selectedCity.lat))))/(cosD*Math.cos(rad(selectedCity.lat)));if(cosH>1||cosH<-1)return null;let H=(rise?360-deg(Math.acos(cosH)):deg(Math.acos(cosH)))/15,T=H+RA-.06571*t-6.622,UT=n24(T-lngH);return n24(UT+selectedCity.tz)}
function decDate(d,h){let hh=Math.floor(h),mf=(h-hh)*60,mm=Math.floor(mf),ss=Math.round((mf-mm)*60);return new Date(d.getFullYear(),d.getMonth(),d.getDate(),hh,mm,ss)}
function fmtTime(d){return toEnglish(d.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}))}
function fmtShort(t){if(!t)return"--";let c=String(t).replace(/\s?\(.+\)/,"").trim().split(":");return toEnglish(`${c[0].padStart(2,"0")}:${c[1].padStart(2,"0")}`)}
function fmtDate(d){return toEnglish(d.toLocaleDateString("ar-QA-u-nu-latn",{weekday:"long",year:"numeric",month:"long",day:"numeric"}))}
function fmtHijri(d){try{return toEnglish(new Intl.DateTimeFormat("ar-SA-u-ca-islamic-nu-latn",{weekday:"long",year:"numeric",month:"long",day:"numeric"}).format(d))}catch{return"--"}}
function duration(ms){let s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return toEnglish(`${h} ساعة ${m} دقيقة ${sec} ثانية`)}
function updateClockSun(){let now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),tom=new Date(today);tom.setDate(today.getDate()+1);let sr=decDate(today,sunTime(today,true)),ss=decDate(today,sunTime(today,false)),srt=decDate(tom,sunTime(tom,true)),sst=decDate(tom,sunTime(tom,false));setText("currentTime",fmtTime(now));setText("currentDate",fmtDate(now));setText("hijriDate",fmtHijri(now));setText("sunriseToday",fmtTime(sr));setText("sunsetToday",fmtTime(ss));setText("dayLengthToday",duration(ss-sr));setText("sunriseTomorrow",fmtTime(srt));setText("sunsetTomorrow",fmtTime(sst))}
async function loadPrayer(){try{let ts=Math.floor(Date.now()/1000),url=`https://api.aladhan.com/v1/timings/${ts}?latitude=${selectedCity.lat}&longitude=${selectedCity.lng}&method=${prayerMethod}`;let data=await(await fetch(url)).json(),t=data.data.timings;prayerTimes={Fajr:fmtShort(t.Fajr),Sunrise:fmtShort(t.Sunrise),Dhuhr:fmtShort(t.Dhuhr),Asr:fmtShort(t.Asr),Maghrib:fmtShort(t.Maghrib),Isha:fmtShort(t.Isha)};["Fajr","Sunrise","Dhuhr","Asr","Maghrib","Isha"].forEach((k,i)=>setText(["fajr","sunrisePrayer","dhuhr","asr","maghrib","isha"][i],prayerTimes[k]));let methodName={2:"MWL",3:"Umm Al-Qura",4:"Qatar"}[prayerMethod]||"Custom";prayerSource.textContent=methodName+" • "+selectedCity.label;planSleep();scheduleAlerts()}catch{prayerSource.textContent="تعذر التحديث"}}
function wdesc(c){return({0:"سماء صافية",1:"غالباً صافي",2:"غائم جزئياً",3:"غائم",45:"ضباب",48:"ضباب كثيف",51:"رذاذ خفيف",53:"رذاذ متوسط",55:"رذاذ كثيف",61:"مطر خفيف",63:"مطر متوسط",65:"مطر غزير",80:"زخات خفيفة",81:"زخات متوسطة",82:"زخات قوية",95:"عواصف رعدية"})[c]||"حالة غير معروفة"}
async function loadWeather(){try{weatherStatus.textContent="مباشر";let url=`https://api.open-meteo.com/v1/forecast?latitude=${selectedCity.lat}&longitude=${selectedCity.lng}&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,precipitation&timezone=auto`;let d=await(await fetch(url)).json(),c=d.current;setText("temperature",`${Math.round(c.temperature_2m)}°C`);weatherDescription.textContent=wdesc(c.weather_code);setText("apparentTemp",`${Math.round(c.apparent_temperature)}°C`);setText("humidity",`${c.relative_humidity_2m}%`);setText("windSpeed",`${Math.round(c.wind_speed_10m)} كم/س`);setText("precipitation",`${c.precipitation||0} mm`);setText("weatherTime",c.time?c.time.replace("T"," "):"--")}catch{weatherStatus.textContent="غير متاح";weatherDescription.textContent="تعذر جلب الطقس"}}
function timeToDate(t,base=new Date()){let [h,m]=t.split(":").map(Number),d=new Date(base);d.setHours(h,m,0,0);return d}
function planSleep(){if(!prayerTimes.Fajr||!prayerTimes.Isha)return;let now=new Date(),fajr=timeToDate(prayerTimes.Fajr),isha=timeToDate(prayerTimes.Isha);if(fajr<now)fajr.setDate(fajr.getDate()+1);let wake=new Date(fajr.getTime()-wakeBeforeFajr*60000);let sleep=new Date(wake.getTime()-sleepHours*3600000);let latestAfterIsha=new Date(isha.getTime()+90*60000);let reason=`لتحصل على ${sleepHours} ساعات نوم وتستيقظ قبل الفجر بـ ${wakeBeforeFajr} دقيقة.`;if(sleep<latestAfterIsha){sleep=latestAfterIsha;reason+= " تم تعديل وقت النوم ليكون بعد العشاء بوقت مناسب."}setText("suggestedSleep",fmtTime(sleep));setText("suggestedWake",fmtTime(wake));sleepReason.textContent=toEnglish(reason)}
function playSound(){new Audio("adhan.mp3").play().catch(()=>{try{let ctx=new(window.AudioContext||window.webkitAudioContext)(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=880;g.gain.value=.08;o.connect(g);g.connect(ctx.destination);o.start();setTimeout(()=>{o.stop();ctx.close()},800)}catch{}})}
function clearAlerts(){alertTimers.forEach(clearTimeout);alertTimers=[]}
function showN(title,body){playSound();new Notification(title,{body,icon:"icon.svg"})}
function scheduleAlerts(){clearAlerts();if(!alertsEnabled||!("Notification"in window)||Notification.permission!=="granted")return;["Fajr","Dhuhr","Asr","Maghrib","Isha"].forEach(k=>{let names={Fajr:"الفجر",Dhuhr:"الظهر",Asr:"العصر",Maghrib:"المغرب",Isha:"العشاء"},d=timeToDate(prayerTimes[k]);if(d<new Date())return;if(alertSettings.before){let ms=d-new Date()-600000;if(ms>0)alertTimers.push(setTimeout(()=>showN(`اقترب وقت صلاة ${names[k]}`,"باقي 10 دقائق"),ms))}if(alertSettings.atTime){let ms=d-new Date();if(ms>0)alertTimers.push(setTimeout(()=>showN(`حان وقت صلاة ${names[k]}`,selectedCity.label),ms))}})}
alertButton.onclick=async()=>{if(!("Notification"in window)){alert("التنبيهات غير مدعومة");return}if(!alertsEnabled){let p=await Notification.requestPermission();if(p!=="granted")return;alertsEnabled=true}else alertsEnabled=false;localStorage.setItem("alertsEnabled",String(alertsEnabled));updateAlertUI();scheduleAlerts()}
function updateAlertUI(){alertButton.textContent=alertsEnabled?"🔕 إيقاف التنبيهات":"🔔 التنبيهات";alertStatus.textContent=alertsEnabled?"مفعلة":"متوقفة";alertStatus.className=alertsEnabled?"alert-on":"alert-off"}
function qibla(lat,lng){let p1=rad(lat),p2=rad(KAABA.lat),dl=rad(KAABA.lng-lng),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return n360(deg(Math.atan2(y,x)))}
function delta(a,b){return((b-a+540)%360)-180} function smooth(cur,next){return cur===null?next:n360(cur+delta(cur,next)*.16)}
function updateQibla(head=null){qiblaBearing=qibla(selectedCity.lat,selectedCity.lng);let rot=qiblaBearing;if(typeof head==="number"&&!Number.isNaN(head)){smoothedHeading=smooth(smoothedHeading,n360(head));rot=n360(qiblaBearing-smoothedHeading);setText("qiblaDegree",`${Math.round(qiblaBearing)}° | الجهاز ${Math.round(smoothedHeading)}°`)}else setText("qiblaDegree",`${Math.round(qiblaBearing)}° من الشمال`);qiblaNeedleWrap.style.transform=`rotate(${rot}deg)`}
function handleOrientation(e){let h=null;if(typeof e.webkitCompassHeading==="number")h=e.webkitCompassHeading;else if(typeof e.alpha==="number")h=360-e.alpha;if(typeof h==="number"&&!Number.isNaN(h))updateQibla(h)}
compassButton.onclick=()=>{if(typeof DeviceOrientationEvent==="undefined"){compassNote.textContent="البوصلة غير مدعومة";return}let start=()=>{window.removeEventListener("deviceorientation",handleOrientation,true);window.removeEventListener("deviceorientationabsolute",handleOrientation,true);window.addEventListener("deviceorientation",handleOrientation,true);window.addEventListener("deviceorientationabsolute",handleOrientation,true);compassNote.textContent="تم التشغيل. حرّك الجوال على شكل 8 للمعايرة."};if(typeof DeviceOrientationEvent.requestPermission==="function"){DeviceOrientationEvent.requestPermission().then(s=>s==="granted"?start():compassNote.textContent="لم يتم السماح بالبوصلة").catch(()=>compassNote.textContent="تعذر تشغيل البوصلة")}else start()}
gpsButton.onclick=()=>{if(!navigator.geolocation){alert("GPS غير مدعوم");return}gpsButton.textContent="📍 جاري التحديد...";navigator.geolocation.getCurrentPosition(async p=>{selectedCity={name:"موقعي الحالي",label:"موقعي",lat:p.coords.latitude,lng:p.coords.longitude,tz:3};localStorage.setItem("selectedCity",JSON.stringify(selectedCity));gpsButton.textContent="📍 موقعي";smoothedHeading=null;await refreshAll()},()=>{gpsButton.textContent="📍 موقعي";alert("تعذر تحديد الموقع")},{enableHighAccuracy:true,timeout:10000})}
function renderAdhkar(){morningList.innerHTML=window.MORNING_ADHKAR.map((x,i)=>`<div class="dhikr"><div class="dua-title">${toEnglish(i+1)}. ذكر الصباح</div><div class="dua-text">${x}</div></div>`).join("");eveningList.innerHTML=window.EVENING_ADHKAR.map((x,i)=>`<div class="dhikr"><div class="dua-title">${toEnglish(i+1)}. ذكر المساء</div><div class="dua-text">${x}</div></div>`).join("")}
function getDuas(){let custom=JSON.parse(localStorage.getItem("customDuas")||"[]");return [...window.PRESET_DUAS,...custom]}
function renderDuas(){let q=(duaSearch.value||"").trim();let list=getDuas().filter(d=>!q||(`${d.title} ${d.category} ${d.text}`).includes(q));duaList.innerHTML=list.map((d,i)=>`<div class="dua-card"><div class="dua-title">${toEnglish(i+1)}. ${d.title} <span class="tag">${d.category||"عام"}</span></div><div class="dua-text">${d.text}</div></div>`).join("")}
addDuaBtn.onclick=()=>{let title=duaTitle.value.trim()||"دعاء جديد",category=duaCategory.value.trim()||"خاص",text=duaText.value.trim();if(!text){alert("اكتب نص الدعاء أولاً");return}let custom=JSON.parse(localStorage.getItem("customDuas")||"[]");custom.unshift({title,category,text});localStorage.setItem("customDuas",JSON.stringify(custom));duaTitle.value=duaCategory.value=duaText.value="";renderDuas()}
duaSearch.oninput=renderDuas;
async function refreshAll(){cityPill.textContent=selectedCity.label;updateClockSun();updateQibla();await Promise.all([loadPrayer(),loadWeather()])}
initTabs();initCity();initSettings();applyDark();updateAlertUI();renderAdhkar();renderDuas();refreshAll();setInterval(updateClockSun,1000);setInterval(loadWeather,20*60*1000);setInterval(loadPrayer,60*60*1000);
