const CITIES=[
{name:"الدوحة - قطر",label:"الدوحة",country:"Qatar",lat:25.2854,lng:51.5310,tz:3},
{name:"عمّان - الأردن",label:"عمّان",country:"Jordan",lat:31.9539,lng:35.9106,tz:3},
{name:"معان - الأردن",label:"معان",country:"Jordan",lat:30.1962,lng:35.7341,tz:3},
{name:"الكرك - الأردن",label:"الكرك",country:"Jordan",lat:31.1853,lng:35.7047,tz:3},
{name:"القدس - فلسطين",label:"القدس",country:"Palestine",lat:31.7683,lng:35.2137,tz:3},
{name:"مكة المكرمة - السعودية",label:"مكة",country:"Saudi Arabia",lat:21.3891,lng:39.8579,tz:3},
{name:"الرياض - السعودية",label:"الرياض",country:"Saudi Arabia",lat:24.7136,lng:46.6753,tz:3},
{name:"دبي - الإمارات",label:"دبي",country:"United Arab Emirates",lat:25.2048,lng:55.2708,tz:4},
{name:"لندن - بريطانيا",label:"لندن",country:"United Kingdom",lat:51.5072,lng:-0.1276,tz:1},
{name:"إسطنبول - تركيا",label:"إسطنبول",country:"Turkey",lat:41.0082,lng:28.9784,tz:3}
];
const KAABA={lat:21.422487,lng:39.826206};
let selectedCity=JSON.parse(localStorage.getItem("selectedCity"))||CITIES[0];
let alertsEnabled=localStorage.getItem("alertsEnabled")==="true";
let darkMode=localStorage.getItem("darkMode")==="true";
let alertSettings=JSON.parse(localStorage.getItem("alertSettings"))||{before:true,atTime:true,prayers:{Fajr:true,Dhuhr:true,Asr:true,Maghrib:true,Isha:true}};
let prayerTimes={},alertTimers=[],deferredPrompt,qiblaBearing=0,smoothedHeading=null;
const el=id=>document.getElementById(id);
function toEnglishNumbers(v){return String(v).replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d)).replace(/[۰-۹]/g,d=>"۰۱۲۳۴۵۶۷۸۹".indexOf(d))}
function setText(id,v){el(id).textContent=toEnglishNumbers(v)}
function initCitySelect(){citySelect.innerHTML="";CITIES.forEach((c,i)=>{const o=document.createElement("option");o.value=i;o.textContent=c.name;if(c.label===selectedCity.label&&Number(c.lat).toFixed(4)===Number(selectedCity.lat).toFixed(4))o.selected=true;citySelect.appendChild(o)});citySelect.addEventListener("change",async()=>{selectedCity=CITIES[Number(citySelect.value)];localStorage.setItem("selectedCity",JSON.stringify(selectedCity));smoothedHeading=null;await refreshAll()})}
function applyDarkMode(){document.body.classList.toggle("dark",darkMode);darkModeButton.textContent=darkMode?"☀️ الوضع الفاتح":"🌙 الوضع الداكن"}
darkModeButton.addEventListener("click",()=>{darkMode=!darkMode;localStorage.setItem("darkMode",String(darkMode));applyDarkMode()});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installButton.style.display="block"});
installButton.addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installButton.style.display="none"});
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");
function toRadians(d){return d*Math.PI/180}function toDegrees(r){return r*180/Math.PI}
function dayOfYear(date){const s=new Date(Date.UTC(date.getFullYear(),0,0));const c=Date.UTC(date.getFullYear(),date.getMonth(),date.getDate());return Math.floor((c-s)/86400000)}
function normalize360(v){v%=360;return v<0?v+360:v}function normalize24(v){v%=24;return v<0?v+24:v}
function calculateSunTime(date,isSunrise){const zenith=90.833,N=dayOfYear(date),lngHour=selectedCity.lng/15,t=N+((isSunrise?6:18)-lngHour)/24,M=.9856*t-3.289;let L=M+1.916*Math.sin(toRadians(M))+.020*Math.sin(toRadians(2*M))+282.634;L=normalize360(L);let RA=toDegrees(Math.atan(.91764*Math.tan(toRadians(L))));RA=normalize360(RA);const Lq=Math.floor(L/90)*90,RAq=Math.floor(RA/90)*90;RA=(RA+(Lq-RAq))/15;const sinDec=.39782*Math.sin(toRadians(L)),cosDec=Math.cos(Math.asin(sinDec));const cosH=(Math.cos(toRadians(zenith))-(sinDec*Math.sin(toRadians(selectedCity.lat))))/(cosDec*Math.cos(toRadians(selectedCity.lat)));if(cosH>1||cosH<-1)return null;let H=isSunrise?360-toDegrees(Math.acos(cosH)):toDegrees(Math.acos(cosH));H/=15;const T=H+RA-.06571*t-6.622,UT=normalize24(T-lngHour);return normalize24(UT+selectedCity.tz)}
function decimalToDate(date,dh){const h=Math.floor(dh),mf=(dh-h)*60,m=Math.floor(mf),s=Math.round((mf-m)*60);return new Date(date.getFullYear(),date.getMonth(),date.getDate(),h,m,s)}
function formatTime(date){return toEnglishNumbers(date.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}))}
function formatPrayerTime(t){if(!t)return"--";const c=String(t).replace(/\s?\(.+\)/,"").trim(),p=c.split(":");if(p.length>=2)return toEnglishNumbers(`${p[0].padStart(2,"0")}:${p[1].padStart(2,"0")}`);return toEnglishNumbers(c)}
function formatDate(date){return toEnglishNumbers(date.toLocaleDateString("ar-QA-u-nu-latn",{weekday:"long",year:"numeric",month:"long",day:"numeric"}))}
function formatHijri(date){try{return toEnglishNumbers(new Intl.DateTimeFormat("ar-SA-u-ca-islamic-nu-latn",{weekday:"long",year:"numeric",month:"long",day:"numeric"}).format(date))}catch{return"--"}}
function formatDuration(ms){const ts=Math.floor(ms/1000),h=Math.floor(ts/3600),m=Math.floor(ts%3600/60),s=ts%60;return toEnglishNumbers(`${h} ساعة ${m} دقيقة ${s} ثانية`)}
function updateClockAndSun(){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);const srT=decimalToDate(today,calculateSunTime(today,true)),ssT=decimalToDate(today,calculateSunTime(today,false)),srM=decimalToDate(tomorrow,calculateSunTime(tomorrow,true)),ssM=decimalToDate(tomorrow,calculateSunTime(tomorrow,false));setText("currentTime",formatTime(now));setText("currentDate",formatDate(now));setText("hijriDate",formatHijri(now));setText("sunriseToday",formatTime(srT));setText("sunsetToday",formatTime(ssT));setText("dayLengthToday",formatDuration(ssT-srT));setText("sunriseTomorrow",formatTime(srM));setText("sunsetTomorrow",formatTime(ssM))}
async function loadPrayerTimes(){try{const today=new Date(),url=`https://api.aladhan.com/v1/timings/${Math.floor(today.getTime()/1000)}?latitude=${selectedCity.lat}&longitude=${selectedCity.lng}&method=4`;const res=await fetch(url),data=await res.json(),timings=data.data.timings;prayerTimes={Fajr:formatPrayerTime(timings.Fajr),Sunrise:formatPrayerTime(timings.Sunrise),Dhuhr:formatPrayerTime(timings.Dhuhr),Asr:formatPrayerTime(timings.Asr),Maghrib:formatPrayerTime(timings.Maghrib),Isha:formatPrayerTime(timings.Isha)};setText("fajr",prayerTimes.Fajr);setText("sunrisePrayer",prayerTimes.Sunrise);setText("dhuhr",prayerTimes.Dhuhr);setText("asr",prayerTimes.Asr);setText("maghrib",prayerTimes.Maghrib);setText("isha",prayerTimes.Isha);el("prayerSource").textContent=selectedCity.label;schedulePrayerAlerts()}catch{el("prayerSource").textContent="تعذر التحديث"}}
function weatherCodeToArabic(code){return({0:"سماء صافية",1:"غالباً صافي",2:"غائم جزئياً",3:"غائم",45:"ضباب",48:"ضباب كثيف",51:"رذاذ خفيف",53:"رذاذ متوسط",55:"رذاذ كثيف",61:"مطر خفيف",63:"مطر متوسط",65:"مطر غزير",71:"ثلج خفيف",80:"زخات خفيفة",81:"زخات متوسطة",82:"زخات قوية",95:"عواصف رعدية"})[code]||"حالة طقس غير معروفة"}
async function loadWeather(){try{el("weatherStatus").textContent="مباشر";const url=`https://api.open-meteo.com/v1/forecast?latitude=${selectedCity.lat}&longitude=${selectedCity.lng}&current=temperature_2m,weather_code,wind_speed_10m&timezone=auto`;const res=await fetch(url),data=await res.json();setText("temperature",`${Math.round(data.current.temperature_2m)}°C`);el("weatherDescription").textContent=weatherCodeToArabic(data.current.weather_code);setText("windSpeed",`${Math.round(data.current.wind_speed_10m)} كم/س`);setText("weatherTime",data.current.time?data.current.time.replace("T"," "):"--")}catch{el("weatherStatus").textContent="غير متاح";el("weatherDescription").textContent="تعذر جلب الطقس حالياً"}}
function prayerTimeToDate(t){const[h,m]=t.split(":").map(Number),d=new Date();d.setHours(h,m,0,0);return d}
function playAlertSound(){new Audio("adhan.mp3").play().catch(()=>beepFallback())}
function beepFallback(){try{const ctx=new(window.AudioContext||window.webkitAudioContext)(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type="sine";osc.frequency.value=880;gain.gain.value=.08;osc.connect(gain);gain.connect(ctx.destination);osc.start();setTimeout(()=>{osc.stop();ctx.close()},800)}catch{}}
async function toggleAlerts(){if(!("Notification"in window)){alert("جهازك أو المتصفح لا يدعم التنبيهات.");return}if(!alertsEnabled){const p=await Notification.requestPermission();if(p!=="granted"){alert("لازم تسمح للتنبيهات من المتصفح أولاً.");return}alertsEnabled=true}else alertsEnabled=false;localStorage.setItem("alertsEnabled",String(alertsEnabled));updateAlertUI();schedulePrayerAlerts()}
function updateAlertUI(){alertButton.textContent=alertsEnabled?"🔕 إيقاف التنبيهات":"🔔 تشغيل التنبيهات";el("alertStatus").textContent=alertsEnabled?"مفعلة":"متوقفة";el("alertStatus").className=alertsEnabled?"alert-on":"alert-off"}
function clearAlertTimers(){alertTimers.forEach(clearTimeout);alertTimers=[]}
function showNotification(title,body){playAlertSound();new Notification(title,{body,icon:"icon.svg"})}
function schedulePrayerAlerts(){clearAlertTimers();if(!alertsEnabled||!prayerTimes||Object.keys(prayerTimes).length===0)return;const names={Fajr:"الفجر",Dhuhr:"الظهر",Asr:"العصر",Maghrib:"المغرب",Isha:"العشاء"};Object.keys(names).forEach(k=>{if(!alertSettings.prayers[k]||!prayerTimes[k])return;const pd=prayerTimeToDate(prayerTimes[k]),now=new Date();if(alertSettings.before){const ms=pd-now-600000;if(ms>0)alertTimers.push(setTimeout(()=>showNotification(`اقترب وقت صلاة ${names[k]}`,`باقي 10 دقائق - ${selectedCity.label}`),ms))}if(alertSettings.atTime){const ms=pd-now;if(ms>0)alertTimers.push(setTimeout(()=>showNotification(`حان وقت صلاة ${names[k]}`,`المدينة: ${selectedCity.label}`),ms))}})}
alertButton.addEventListener("click",toggleAlerts);testSoundButton.addEventListener("click",playAlertSound);
function initAlertSettings(){el("notifyBefore").checked=alertSettings.before;el("notifyAtTime").checked=alertSettings.atTime;el("notifyBefore").addEventListener("change",e=>{alertSettings.before=e.target.checked;saveAlertSettings()});el("notifyAtTime").addEventListener("change",e=>{alertSettings.atTime=e.target.checked;saveAlertSettings()});document.querySelectorAll(".prayer-toggle").forEach(input=>{input.checked=alertSettings.prayers[input.dataset.prayer];input.addEventListener("change",e=>{alertSettings.prayers[e.target.dataset.prayer]=e.target.checked;saveAlertSettings()})})}
function saveAlertSettings(){localStorage.setItem("alertSettings",JSON.stringify(alertSettings));schedulePrayerAlerts()}
function getQiblaBearing(lat,lng){const p1=toRadians(lat),p2=toRadians(KAABA.lat),dl=toRadians(KAABA.lng-lng),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return normalize360(toDegrees(Math.atan2(y,x)))}
function shortestAngleDelta(from,to){return((to-from+540)%360)-180}
function smoothHeading(current,next){if(current===null)return next;return normalize360(current+shortestAngleDelta(current,next)*.18)}
function updateQibla(deviceHeading=null){qiblaBearing=getQiblaBearing(selectedCity.lat,selectedCity.lng);let rotation=qiblaBearing;if(typeof deviceHeading==="number"&&!Number.isNaN(deviceHeading)){smoothedHeading=smoothHeading(smoothedHeading,normalize360(deviceHeading));rotation=normalize360(qiblaBearing-smoothedHeading);setText("qiblaDegree",`${Math.round(qiblaBearing)}° | الجهاز: ${Math.round(smoothedHeading)}°`)}else setText("qiblaDegree",`${Math.round(qiblaBearing)}° من الشمال`);el("qiblaNeedleWrap").style.transform=`rotate(${rotation}deg)`}
function enableCompass(){if(typeof DeviceOrientationEvent==="undefined"){el("compassNote").textContent="البوصلة غير مدعومة على هذا المتصفح.";return}const start=()=>{window.removeEventListener("deviceorientationabsolute",handleOrientation,true);window.removeEventListener("deviceorientation",handleOrientation,true);window.addEventListener("deviceorientationabsolute",handleOrientation,true);window.addEventListener("deviceorientation",handleOrientation,true);el("compassNote").textContent="تم تشغيل البوصلة. للحصول على دقة أفضل حرّك الجوال على شكل رقم 8 وابتعد عن المعادن."};if(typeof DeviceOrientationEvent.requestPermission==="function"){DeviceOrientationEvent.requestPermission().then(s=>s==="granted"?start():el("compassNote").textContent="لم يتم السماح باستخدام البوصلة.").catch(()=>el("compassNote").textContent="تعذر تشغيل البوصلة.")}else start()}
function handleOrientation(event){let heading=null;if(typeof event.webkitCompassHeading==="number")heading=event.webkitCompassHeading;else if(typeof event.alpha==="number")heading=360-event.alpha;if(typeof heading==="number"&&!Number.isNaN(heading))updateQibla(heading)}
compassButton.addEventListener("click",enableCompass);
gpsButton.addEventListener("click",()=>{if(!navigator.geolocation){alert("الموقع غير مدعوم على هذا الجهاز.");return}gpsButton.textContent="📍 جاري التحديد...";navigator.geolocation.getCurrentPosition(async p=>{selectedCity={name:"موقعي الحالي",label:"موقعي",country:"Current Location",lat:p.coords.latitude,lng:p.coords.longitude,tz:3};localStorage.setItem("selectedCity",JSON.stringify(selectedCity));citySelect.value="";gpsButton.textContent="📍 موقعي";smoothedHeading=null;await refreshAll()},()=>{gpsButton.textContent="📍 موقعي";alert("تعذر تحديد الموقع. تأكد من السماح للموقع من المتصفح.")},{enableHighAccuracy:true,timeout:10000})});
async function refreshAll(){el("cityPill").textContent=selectedCity.label;updateClockAndSun();updateQibla();await Promise.all([loadPrayerTimes(),loadWeather()])}
initCitySelect();initAlertSettings();applyDarkMode();updateAlertUI();refreshAll();setInterval(updateClockAndSun,1000);setInterval(loadWeather,20*60*1000);setInterval(loadPrayerTimes,60*60*1000);
